---
fn_manual_crop_coordinates: resources/manual_coordinates.csv
fn_path_cpproj: 20191211_analysis_HubMAP_LN_Spleen_thymus.cpproj
fn_path_ilp: HubMAP_20191211.ilp
fn_path_ome: Hubmap2020_ome.zip
fn_path_panel: 20191128_HubMAP.csv
fol_path_base: /home/vitoz/Data/SegData/HuBMAP/20191211_analysis_HubMAP_LN_Spleen_thymus
re_label_basic: (?P<cropname>.*)_label\.tiff
re_label_crop: (?P<basename>.*)_ilastik_(?P<suffix>.*)
re_label_suffix: "x(?P<x>[0-9]+)_y(?P<y>[0-9]+)_w(?P<w>[0-9]+)_h(?P<h>[0-9]+)"

fol_path_output: HubMAP2020

default_crop_size: (250,250,1)
