from pathlib import Path
import pandas as pd
import re
import shutil
import pathlib
from snakemake.utils import validate
include: 'rules/cellprofiler.smk'
include: 'rules/ilastik.smk'
# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

#configfile: 'config/config_prepare.yml'

# Allow users to fix the underlying OS via singularity.
#singularity: "docker://votti/miniconda3mamba:v0.4.2"
conda: 'envs/env_base.yaml'
validate(config, "schemas/config_evaluate.schema.yml")

cp_plugins = 'resources/ImcPluginsCP/plugins'

cellprofiler_container = 'docker://cellprofiler/cellprofiler:4.0.7'
ilastik_container = 'docker://ilastik/ilastik-from-binary:1.3.3post3'
ilastik_python = '/ilastik-release/bin/python'
imctools_container = config['varia']['imctools_container']

config_ilastik = {
    'container': ilastik_container,
    'threads': 8,
    'mem_mb': 10000
}

ilastik_container = config_ilastik['container']
ilastik_threads = config_ilastik['threads']
ilastik_mem_mb = config_ilastik['mem_mb']
# Input
# Regular expressions to extract data from crop filenames
# params
# Output
fol_path_results = Path(config['project_id'])

file_path_panel = fol_path_results / 'panel.csv'

fn_config_prepare_data = config['config_prepare']
project_id = config['project_id']
csv_metal = config['csv_metal']
csv_stack_ilastik = config['csv_stack_ilastik']
config_stacks = {'ilastik': {'col_bool': csv_stack_ilastik,
                                     'min_image_size': 50}}

fol_path_project = pathlib.Path(f"{project_id}")
suffix_probablities ='_Probabilities'
suffix_tiff = '.tiff'



subworkflow prepare_data:
    workdir: '../../prepare_data/'
    snakefile:
             "../../prepare_data/workflow/Snakefile"
    configfile:
              fn_config_prepare_data

fn_path_panel = prepare_data(str(fol_path_project / 'panel.csv'))
fol_path_ome = prepare_data(str(fol_path_project / 'ome'))
file_path_img_meta = prepare_data(str(fol_path_project / 'training_image_meta.csv'))
fol_path_ilastik_cropinput = fol_path_project / 'ilastik_cropinput'
fol_path_labels=prepare_data(str(fol_path_project / 'training_labels')),
file_path_feature_matrix=prepare_data(str(fol_path_project / 'feature_matrix.txt')),

# Output:
file_path_ilastik_all = fol_path_project / 'ilastik_trained_full.ilp'
fol_pat_stack = fol_path_results / 'stacks_{stack}'
fol_path_stack_ilastik = str(fol_pat_stack).format(**{'stack': 'ilastik'})
fol_path_ilastik_crops = fol_path_results / 'ilastik_crops'

fol_path_probab_all = fol_path_project / 'probabilities_all'

has_all = fol_path_project / 'all'

rule all:
    input: fol_path_stack_ilastik, fol_path_ilastik_crops,
         file_path_ilastik_all, fol_path_probab_all
    output: touch(has_all)


rule ome2analysis:
    input:
         fol_ome = fol_path_ome,
         panel = fn_path_panel
    output:
          directory(str(fol_pat_stack))
    container:
             imctools_container
    params:
          column_used = lambda wildcards: config_stacks[wildcards.stack][
              'col_bool'],
          column_metal = csv_metal,
          suffix = '_{stack}',
          min_imgsize = lambda wildcards: config_stacks[wildcards.stack][
              'min_image_size']
    threads: 32
    script:
          'scripts/imc2analysis.py'

rule crop_reproduction_input:
    input:
        fol_ilastik=fol_path_stack_ilastik,
        fn_cropmeta=file_path_img_meta
    output:
        fol_cropinput=directory(fol_path_ilastik_cropinput)
    run:
        fol_cropinput = Path(output.fol_cropinput)
        fol_ilastik = Path(input.fol_ilastik)
        dat_cropmeta = pd.read_csv(input.fn_cropmeta)
        fol_cropinput.mkdir()
        for _, row in dat_cropmeta.iterrows():
            fn_inp = fol_ilastik / f"{row['basename']}_ilastik.tiff"
            fn_out = fol_cropinput / f"{row['cropname']}.tiff"
            fn_out.symlink_to(fn_inp.resolve())

rule get_trained_classifier:
    input:
        fol_labels=fol_path_labels,
         fol_imgs=fol_path_ilastik_crops,
         fn_feature_matrix=file_path_feature_matrix,
         fn_file_meta=file_path_img_meta
    params:
        glob_img=lambda wildcards: '"{basename}_x{x}_y{y}_w{w}_h{h}.h5"'
    output:
        file_path_ilastik_all
    container: ilastik_container
    shell:
        """
        {ilastik_python} workflow/scripts/train_headless.py {output[0]}\
            {input.fol_imgs} \
            {input.fol_labels} \
            {input.fn_file_meta} \
            {input.fn_feature_matrix} \
            {params.glob_img}
            
        """


config_dict_cp = {
        'ilastik_crops':
{
        'message':  """\
                    Prepare ilastik crops
                    
                    This will prepare ilastik crops by reproducing
                    the pre-labeled                    
                    """,
        'run_size': 3,
        'plugins': cp_plugins,
        'pipeline': 'resources/1_prepare_ilastik.cppipe',
        'input_files': [
            fol_path_ilastik_cropinput,
            file_path_img_meta
        ],
        'output_patterns': {'.':
                            directory(fol_path_ilastik_crops)},
        'input_folder': prepare_data(str(fol_path_project))
    }
                 }

config_dict_ilastik = {
    'all':
        {'message': """\
                    Runs ilastik classifier run on full dataset
                    """,
         'project': str(file_path_ilastik_all),
         'run_size': 4,
         'output_format': 'tiff',
         'output_filename': f'{{nickname}}{suffix_probablities}{suffix_tiff}',
         'export_source': 'Probabilities',
         'export_dtype': 'uint16',
         'pipeline_result_drange': '"[0.0, 1.0]"',
         'export_drange': '"[0, 65535]"',
         'input_files':
         # Folder containing process hdf5
         # images for ilastik pixel classification
             fol_path_ilastik_crops,
         'output_pattern':
         # Folder containing probability maps for segmentation
             directory(fol_path_probab_all)
         }
}

define_cellprofiler_rules(config_dict_cp, fol_path_results, container_cp=cellprofiler_container)
define_ilastik_rules(config_dict_ilastik, fol_path_results, threads=ilastik_threads,
                     mem_mb=ilastik_mem_mb, container_ilastik=ilastik_container)
